### ISSUE TITLE
pre set credit not work

### ISSUE THREAD

**Issue by smartstudyplatform** [bdecentgmbh/moodle-enrol_credit#7]
i set the default value as 5 , so that any new user get credit of 5 , but when i test it for new user , it appear in the user profile 5 credit as expected, but on a test course that i made a 5 credit require it show that the test user balance is zero , again from site admin when edit the user profile , and the log in with test user it works !

**Comment by stefanscholz** [comment]
Hi!

I can reproduce that behaviour, but it is not really related to credit enrolment and therefor nothing we can change unfortunately.

See, if you set a default value for a custom profile field, it is in my experience not immediately stored in the user profile. It is shown on the profile page, which is weird, but it is not really there. 

I know that another customer has changed the field type in the database manually (moodle does not have a profile field type "number") and has reported that it would work then. I've never tried that myself though. You can about it in the comments section of the plugin on moodle.org

Can you confirm that if you edit the user profile without changing anything and then saving it, it will then work? (That's what I can reproduce)

We usually do not use the default value by the profile field, but instead credits uploaded using csv files, added manually or via web service.

In one platform, we overcame the problem by forcing the user after registration to open the profile and save it once - you can even reward the user with a badge for that by the way. (We used the trick to require not all fields during account registration, and later on asked to fill in those fields)

Let me know if you can confirm my observation.

Best
Stefan

**Comment by stefanscholz** [comment]
No response from reporter, therefore closing issue.
